export const stateOfBuilding = {
  1: 'nieuw',
  2: 'uitstekend',
  3: 'hernieuwd',
  4: 'goede staat',
  5: 'deels te renoveren',
  6: 'te renoveren',
  7: 'te hermaken',
  8: 'af te breken',
  9: 'niet gekend',
  10: 'Groen vastgoed',
  11: 'te bouwen',
  12: 'ruwbouw',
  13: 'nieuwbouw project',
  14: 'kleine werken',
  15: 'gerenoveerd',
  16: 'concept',
  17: 'ontwikkeld',
  18: 'klaar om te starten',
  19: 'water- en winddicht',
  20: 'afgewerkt',
  21: 'opgeleverd',
  22: 'gepleisterd',
  23: 'terrein nog af te werken',
  24: 'terrein klaar voor constructie',
};

export const availabilityOfBuilding = {
  1: 'vanaf akte',
  2: 'af te spreken met eigenaar',
  3: 'mits inachtneming huurders',
  4: 'niet beschikbaar',
  5: 'onmiddellijk',
  6: 'bij oplevering',
  7: 'in onderling overleg',
};
